- name: Setup Kubernetes Cluster
  hosts: all
  become: yes
 
  tasks:
    - name: Update and install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
          - socat
        state: present
        update_cache: yes
 
    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0
 
    - name: Ensure swap is disabled on boot
      replace:
        path: /etc/fstab
        regexp: '^\s*([^#\s]\S+)\s+(\S+)\s+swap\s+'
        replace: '#\1 \2 swap'
 
    - name: Configure sysctl for Kubernetes networking
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
 
    - name: Apply sysctl settings
      command: sysctl --system
 
    - name: Add kernel modules for Containerd
      copy:
        dest: /etc/modules-load.d/containerd.conf
        content: |
          overlay
          br_netfilter
 
    - name: Load kernel modules
      shell: modprobe overlay && modprobe br_netfilter
 
    - name: Install containerd
      apt:
        name: containerd
        state: present
 
    - name: Create containerd config directory
      file:
        path: /etc/containerd
        state: directory
 
    - name: Generate default containerd config
      shell: containerd config default > /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml
 
    - name: Enable SystemdCgroup
      replace:
        path: /etc/containerd/config.toml
        regexp: '^[# ]*SystemdCgroup = false'
        replace: 'SystemdCgroup = true'
 
    - name: Restart containerd
      service:
        name: containerd
        state: restarted
        enabled: yes
 
    - name: Download Kubernetes release key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
        dest: /etc/apt/keyrings/Release.key
        mode: '0644'
 
    - name: Convert Release.key to GPG
      command: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /etc/apt/keyrings/Release.key
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
 
    - name: Add Kubernetes repo
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"
        filename: kubernetes
        state: present
        update_cache: yes
 
    - name: Install Kubernetes components
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes
 
